CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password TEXT NOT NULL,
    salt VARCHAR(255) NOT NULL,
    type BOOLEAN DEFAULT FALSE,
    emergencyEmail VARCHAR(255) DEFAULT NULL,
    emergencyPhone VARCHAR(255) DEFAULT NULL,
    forgotToken VARCHAR(36) DEFAULT NULL UNIQUE,
    registrationToken VARCHAR(36) DEFAULT NULL UNIQUE,
    sessionToken VARCHAR(36) DEFAULT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS products (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL,
    tag VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    image TEXT DEFAULT NULL,
    stock INTEGER DEFAULT NULL,
    category VARCHAR(255) NOT NULL,
    stars REAL DEFAULT NULL,
    owner INTEGER NOT NULL,
    FOREIGN KEY(owner) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS reviews (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    stars INTEGER NOT NULL,
    comment TEXT NOT NULL,
    product INTEGER NOT NULL,
    user INTEGER NOT NULL,
    FOREIGN KEY(product) REFERENCES products(id),
    FOREIGN KEY(user) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS orders (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    buyer INTEGER NOT NULL,
    product INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    signature TEXT NOT NULL,
    FOREIGN KEY(buyer) REFERENCES users(id),
    FOREIGN KEY(product) REFERENCES products(id)
);

CREATE TABLE IF NOT EXISTS chat(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user1 INTEGER NOT NULL,
    user2 INTEGER NOT NULL,
    message TEXT NOT NULL,
    time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(user1) REFERENCES users(id),
    FOREIGN KEY(user2) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS rsaKeys(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user INTEGER NOT NULL,
    e BIGINT NOT NULL,
    d BIGINT NOT NULL,
    n BIGINT NOT NULL,
    FOREIGN KEY(user) REFERENCES users(id)
);


